
change-template: '- #$NUMBER $TITLE @$AUTHOR'
sort-direction: ascending
categories:
  - title: 'Dependencies'
    collapse-after: 1
    labels:
      - 'dependencies'
template: |
  ## What’s Changed

  $CHANGES